#!/usr/bin/env bash
rm -rf MANUAL.md
touch MANUAL.md
echo "\`\`\`lisp" >> MANUAL.md
go run cmd/man/main.go >> MANUAL.md 2>&1
echo "\`\`\`" >> MANUAL.md
./export_to_chat > chat.txt


git add .
git commit -m "auto_push"
git push
